baseurl = "https://redwallanalytics.com"
languageCode = "en-us"
title = "Redwall Analytics"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Redwall Analytics"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/david-lucey-cfa-cpa-mba-msba"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lucey_david"
    weight = 5
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/luceydav"
    weight = 6
   

[params]
    description = "A Website for Sharing Research Explorations in R"

    mainSections = ["post"]

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.icon]
    url = "favicon.ico"

